services:
  lsa-backend:
    image: ghcr.io/manangandhi1810/lsa-backend:latest
    container_name: lsa-backend
    restart: unless-stopped
    ports:
      - 8080:8080/tcp
    env_file:
      - .env

  lsa-frontend:
    image: ghcr.io/manangandhi1810/lsa-frontend:latest
    container_name: lsa-frontend
    restart: unless-stopped
    ports:
      - 3000:3000/tcp
    depends_on:
      - lsa-backend
    env_file:
      - .env